// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73aVkVYsp3JD7jOs_Yylimq4vY9IxvEo',
    appId: '1:401659988517:web:fe278a599fd1aaadad8dcc',
    messagingSenderId: '401659988517',
    projectId: 'fiap-m05-hackaton',
    authDomain: 'fiap-m05-hackaton.firebaseapp.com',
    storageBucket: 'fiap-m05-hackaton.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIxHpCXTUZysfjw0SThSGGj2vxKapl0gk',
    appId: '1:401659988517:android:057c7fa361ad9a30ad8dcc',
    messagingSenderId: '401659988517',
    projectId: 'fiap-m05-hackaton',
    storageBucket: 'fiap-m05-hackaton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfvVLFVY9uzH0Lo0NMcvsQTVgLjCo998A',
    appId: '1:401659988517:ios:171695f50ced31a3ad8dcc',
    messagingSenderId: '401659988517',
    projectId: 'fiap-m05-hackaton',
    storageBucket: 'fiap-m05-hackaton.firebasestorage.app',
    iosClientId: '401659988517-b3k5799c9mc7er143blnblrd6i16lfhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiapHackatonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfvVLFVY9uzH0Lo0NMcvsQTVgLjCo998A',
    appId: '1:401659988517:ios:171695f50ced31a3ad8dcc',
    messagingSenderId: '401659988517',
    projectId: 'fiap-m05-hackaton',
    storageBucket: 'fiap-m05-hackaton.firebasestorage.app',
    iosClientId: '401659988517-b3k5799c9mc7er143blnblrd6i16lfhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiapHackatonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73aVkVYsp3JD7jOs_Yylimq4vY9IxvEo',
    appId: '1:401659988517:web:fb54fe9d175e3ee3ad8dcc',
    messagingSenderId: '401659988517',
    projectId: 'fiap-m05-hackaton',
    authDomain: 'fiap-m05-hackaton.firebaseapp.com',
    storageBucket: 'fiap-m05-hackaton.firebasestorage.app',
  );
}
